"""Preference dataset construction for the coaching fine-tune.

This is the notebook's data pipeline, rebuilt so it actually runs. The original
had three defects that silently produced an empty or wrong dataset:

1. It concatenated two ``datasets.Dataset`` objects with ``+``, which is not
   supported — and the psychology set uses ``question``/``response_j``/
   ``response_k``, not ``prompt``/``chosen``/``rejected``, so the validation
   pass would have discarded every row anyway.
2. The "rejected" coaching response was generated by splicing the user's own
   first word into a canned sentence, which teaches the model that rejected
   replies start with the user's words rather than that they are directive.
3. Nothing deduplicated or length-filtered, so near-identical pairs and
   one-word responses both made it into training.

What the pairs teach, in both source datasets, is one preference: reflective
and curious over dismissive and directive.
"""

from __future__ import annotations

import hashlib
import itertools
import random
import re
from collections.abc import Iterable, Iterator
from dataclasses import dataclass, field
from typing import Any

from aura.logging import get_logger

log = get_logger(__name__)

PSYCHOLOGY_DATASET = "jkhedri/psychology-dataset"
COACHING_DATASET = "drublackberry/hbr-coaching-real-leaders"

# Appended to preferred psychology answers so the model learns to hand the turn
# back rather than close it down. Kept varied to avoid a learned tic.
COACHING_INVITATIONS: tuple[str, ...] = (
    "What feels most important to you as you sit with this?",
    "Where would you like to start with it?",
    "What would you want to be different a month from now?",
    "What support would actually help right now?",
    "What's one small thing that feels possible today?",
    "What matters most to you in this situation?",
    "How would you like to move forward with it?",
    "What would 'better' look like for you here?",
)

# Rejected responses model the two failure modes the coach must avoid:
# dismissal and unsolicited instruction. They are generic on purpose — the
# signal should be the *stance*, not any content that leaks from the prompt.
DIRECTIVE_REJECTIONS: tuple[str, ...] = (
    "You just need to stop overthinking it and take action. Make a decision "
    "today and move on.",
    "Honestly, this isn't a big deal. Plenty of people have it much worse — "
    "you should focus on being grateful.",
    "Here's what you do: make a list, prioritise it, and execute. The problem "
    "is that you're being too emotional about this.",
    "You should have handled this differently from the start. Going forward, "
    "just be more disciplined and it will sort itself out.",
    "Stop dwelling on it. Distract yourself, keep busy, and it will pass on "
    "its own.",
    "That's simple — quit and find something else. Don't waste time analysing "
    "your feelings about it.",
)

_WHITESPACE = re.compile(r"\s+")


@dataclass
class PreferencePair:
    prompt: str
    chosen: str
    rejected: str
    source: str = "unknown"

    def as_dict(self) -> dict[str, str]:
        return {"prompt": self.prompt, "chosen": self.chosen, "rejected": self.rejected}


@dataclass
class BuildStats:
    """Why rows were dropped — printed at the end of a build."""

    seen: int = 0
    kept: int = 0
    dropped: dict[str, int] = field(default_factory=dict)

    def drop(self, reason: str) -> None:
        self.dropped[reason] = self.dropped.get(reason, 0) + 1

    def summary(self) -> str:
        detail = ", ".join(
            f"{reason}={count}" for reason, count in sorted(self.dropped.items())
        )
        return f"kept {self.kept}/{self.seen}" + (f" (dropped: {detail})" if detail else "")


def normalise(text: Any) -> str:
    return _WHITESPACE.sub(" ", str(text or "")).strip()


def validate(
    pair: PreferencePair,
    stats: BuildStats,
    *,
    min_prompt: int = 20,
    min_response: int = 40,
    max_chars: int = 4000,
) -> bool:
    """Reject pairs that would teach the model nothing, or the wrong thing."""
    stats.seen += 1
    if len(pair.prompt) < min_prompt:
        stats.drop("prompt_too_short")
        return False
    if len(pair.chosen) < min_response or len(pair.rejected) < min_response:
        stats.drop("response_too_short")
        return False
    if max(len(pair.prompt), len(pair.chosen), len(pair.rejected)) > max_chars:
        stats.drop("too_long")
        return False
    if pair.chosen.strip().lower() == pair.rejected.strip().lower():
        stats.drop("identical_pair")
        return False
    stats.kept += 1
    return True


def _fingerprint(pair: PreferencePair) -> str:
    return hashlib.sha1(
        f"{pair.prompt.lower()}|{pair.chosen.lower()}".encode()
    ).hexdigest()


def deduplicate(pairs: Iterable[PreferencePair]) -> list[PreferencePair]:
    seen: set[str] = set()
    unique: list[PreferencePair] = []
    for pair in pairs:
        key = _fingerprint(pair)
        if key not in seen:
            seen.add(key)
            unique.append(pair)
    return unique


# --------------------------------------------------------------------------
# Sources
# --------------------------------------------------------------------------


def build_psychology_pairs(
    dataset: Iterable[dict[str, Any]], stats: BuildStats, *, limit: int | None = None
) -> Iterator[PreferencePair]:
    """``question`` + preferred (``response_j``) vs dispreferred (``response_k``)."""
    for index, row in enumerate(dataset):
        if limit is not None and index >= limit:
            break
        prompt = normalise(row.get("question"))
        chosen = normalise(row.get("response_j"))
        rejected = normalise(row.get("response_k"))
        if not (prompt and chosen and rejected):
            stats.seen += 1
            stats.drop("missing_field")
            continue
        # Hand the turn back, so preference also covers "ends with an opening".
        invitation = COACHING_INVITATIONS[index % len(COACHING_INVITATIONS)]
        pair = PreferencePair(prompt, f"{chosen}\n\n{invitation}", rejected, "psychology")
        if validate(pair, stats):
            yield pair


def build_coaching_pairs(
    dataset: Iterable[dict[str, Any]], stats: BuildStats, *, seed: int = 3407
) -> Iterator[PreferencePair]:
    """Real coach turns as ``chosen``; a generic directive reply as ``rejected``.

    Only assistant turns that ask a question are taken, because the question is
    the coaching move we are trying to reinforce.
    """
    rng = random.Random(seed)
    for row in dataset:
        messages = row.get("messages") or []
        for current, following in itertools.pairwise(messages):
            if current.get("role") != "user" or following.get("role") != "assistant":
                continue
            client = normalise(current.get("content"))
            coach = normalise(following.get("content"))
            if "?" not in coach:
                stats.seen += 1
                stats.drop("no_question")
                continue
            pair = PreferencePair(client, coach, rng.choice(DIRECTIVE_REJECTIONS), "coaching")
            if validate(pair, stats):
                yield pair


# --------------------------------------------------------------------------
# Assembly
# --------------------------------------------------------------------------


def build_preference_dataset(
    *,
    psychology_limit: int | None = 3000,
    seed: int = 3407,
    eval_fraction: float = 0.05,
) -> tuple[Any, Any | None]:
    """Load both sources and return ``(train, eval)`` HuggingFace datasets."""
    from datasets import Dataset, load_dataset

    stats = BuildStats()
    pairs: list[PreferencePair] = []

    log.info("loading %s", PSYCHOLOGY_DATASET)
    split = f"train[:{psychology_limit}]" if psychology_limit else "train"
    psychology = load_dataset(PSYCHOLOGY_DATASET, split=split)
    pairs.extend(build_psychology_pairs(psychology, stats, limit=psychology_limit))
    log.info("psychology pairs: %d", len(pairs))

    log.info("loading %s", COACHING_DATASET)
    try:
        coaching = load_dataset(COACHING_DATASET, split="train")
        before = len(pairs)
        pairs.extend(build_coaching_pairs(coaching, stats, seed=seed))
        log.info("coaching pairs: %d", len(pairs) - before)
    except Exception as exc:  # the coaching set is optional, not required
        log.warning("skipping the coaching dataset: %s", exc)

    pairs = deduplicate(pairs)
    random.Random(seed).shuffle(pairs)
    log.info("dataset built — %s, %d unique pairs", stats.summary(), len(pairs))

    if not pairs:
        raise RuntimeError("no usable preference pairs were produced")

    rows = [pair.as_dict() for pair in pairs]
    if eval_fraction <= 0 or len(rows) < 40:
        return Dataset.from_list(rows), None

    cut = max(1, int(len(rows) * eval_fraction))
    return Dataset.from_list(rows[cut:]), Dataset.from_list(rows[:cut])


def to_sft_dataset(preference_dataset: Any, tokenizer: Any) -> Any:
    """Project preference pairs to SFT text by keeping only ``chosen``."""
    from datasets import Dataset

    rows = []
    for row in preference_dataset:
        conversation = [
            {"role": "user", "content": row["prompt"]},
            {"role": "assistant", "content": row["chosen"]},
        ]
        text = tokenizer.apply_chat_template(
            conversation, tokenize=False, add_generation_prompt=False
        )
        rows.append({"text": text.removeprefix("<bos>")})
    return Dataset.from_list(rows)
